---
title: MCF10a Global Chromatin Profilie analysis
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE,  message=FALSE, warning = FALSE, fig.height=10, fig.width=10)

library(scales)
library(RColorBrewer)
#library(MDDRPPA)
library(classInt)
library(tidyverse)


```

```{r functions}

diverge.color <- function(data,pal_choice="RdGy",centeredOn=0){
  nHalf=50
  Min <- min(data,na.rm=TRUE)
  Max <- max(data,na.rm=TRUE)
  Thresh <- centeredOn
  pal<-brewer.pal(n=11,pal_choice)
  rc1<-colorRampPalette(colors=c(pal[1],pal[2]),space="Lab")(10)
  for(i in 2:10){
    tmp<-colorRampPalette(colors=c(pal[i],pal[i+1]),space="Lab")(10)
    rc1<-c(rc1,tmp)
  }
  rb1 <- seq(Min, Thresh, length.out=nHalf+1)
  rb2 <- seq(Thresh, Max, length.out=nHalf+1)[-1]
  rampbreaks <- c(rb1, rb2)
  cuts <- classIntervals(data, style="fixed",fixedBreaks=rampbreaks)
  return(list(cuts,rc1))
}


####global parameters
cols <- brewer.pal(9,"OrRd")
spectralPal <- brewer.pal(11,"Spectral")
blRdPal <- brewer.pal(11,"RdBu")[11:1]


#Values used for out of bounds values
lowProb <- .02
upProb <- .98

#Filter threshold for Biomarker variances
varianceCut <- 0.04

#fold change threshold
fcThresh <- 1.5
z_score_thresh <- 1.5

#Create a function that takes in a vector and returns a same-length vector of z scores 
z_score <- function(x) (x-mean(x, na.rm = TRUE))/sqrt(var(x, na.rm = TRUE))

```


```{r getData}

ProbeMetadata <- read_delim("Data/ProbeMetadata.txt", 
                            "\t", escape_double = FALSE, trim_ws = TRUE)

GCP_Data <- read_tsv("Data/GCP_MCF10a_log2_noProbeMetadata.txt", skip = 2) %>%
  t() %>%
  as.tibble()

# w1<- GCP_Data %>%
#   filter(pert_batch_internal_compound_enumerator == "W1")
# w2<- GCP_Data %>%
#   filter(pert_batch_internal_compound_enumerator == "W2")
# w3<- GCP_Data %>%
#   filter(pert_batch_internal_compound_enumerator == "W3")
# w4<- GCP_Data %>%
#   filter(pert_batch_internal_compound_enumerator == "W4")
# w5<- GCP_Data %>%
#   filter(pert_batch_internal_compound_enumerator == "W5")


colnames(GCP_Data) <- GCP_Data[1,]
GCP_Data <- GCP_Data %>%
  slice(-1) %>%
  mutate_at(vars(matches("^H3K")), as.numeric) %>%
  filter(!is.na(id)) %>%
  mutate(pert_time = factor(pert_time, levels = c(0,1,4,8,24,48)))

#Calculate z scores within weeks
GCP_z <- GCP_Data %>%
  select(matches("^H3K|_compound_|pert_iname|pert_time$|det_well")) %>%
  gather(key=probe_id, value = value, -pert_batch_internal_compound_enumerator,-pert_iname,-pert_time, -det_well) %>%
  group_by(pert_batch_internal_compound_enumerator, probe_id) %>%
  mutate(value_z = z_score(value)) %>%
  ungroup()

```


```{r batchEDA, fig.width = 7, fig.height=5.5, eval = TRUE}
df <- GCP_Data %>%
  select(pert_batch_internal_compound_enumerator, pert_batch_internal_replicate, pert_iname, pert_time) %>%
  distinct()

p <- ggplot(df, aes(x = pert_batch_internal_compound_enumerator, y = pert_batch_internal_replicate, colour = pert_iname, shape = pert_time)) + 
  #geom_point() +
  geom_jitter(alpha = .7, size = 6, width = .3, height = .3) +
  labs(x = "Week",
       y = "Replicate",
       title = "Replicate batches are spread over five weeks",
       subtitle = "PBS_0 and EGF_48 are only conditions in every week")
p
```


```{r processingPlate, fig.width= 3.5, fig.height=2.2}
#recreate the GCP processing plate and color each well by median raw and Z score values

df <- GCP_z %>%  
  group_by(det_well, pert_batch_internal_compound_enumerator) %>%
  summarise(value = median(value, na.rm = TRUE),
            value_z = median(value_z, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(row = str_remove(det_well,"[[:digit:]]+"),
         column = str_remove(det_well,"[[:alpha:]]"),
         column = as.integer(column))


p <- ggplot(df , aes(x = column, y = row, fill = pert_batch_internal_compound_enumerator)) +
  geom_tile() +
  scale_y_discrete(limits=LETTERS[8:1]) +
  scale_x_continuous(breaks = 1:12) +
  labs(title = "GCP processing plate",
       fill = "Week")
p

p <- ggplot(df , aes(x = column, y = row, fill = value)) +
  geom_tile() +
  scale_y_discrete(limits=LETTERS[8:1]) +
  scale_x_continuous(breaks = 1:12) +
  labs(title = "GCP processing plate",
       subtitle = "colored by raw value")
p

p <- ggplot(df , aes(x = column, y = row, fill = value_z)) +
  geom_tile() +
  scale_y_discrete(limits=LETTERS[8:1]) +
  scale_x_continuous(breaks = 1:12) +
  labs(title = "GCP processing plate",
       subtitle = "colored by raw z score")
p

```


### Batch effect removal  
Assumptions are that most of the batch effect comes from the week the samples were grown and the each week the mix of ligands is similar enough to not biologically bias the mean or variance of the values.  

#### Method  
Group by week and probe  
Calcuate z scores on log2 of raw data  
Calculate median EGF value for each probe at each time point  


```{r}
df <- GCP_Data %>%
  select(matches("^H3K|_compound_|pert_iname|pert_time$")) %>%
  gather(key=probe_id, value = value, -pert_batch_internal_compound_enumerator,-pert_iname,-pert_time) %>%
  filter(pert_time==0&pert_iname=="PBS"|pert_time==48&pert_iname=="EGF")

p <- ggplot(df, aes(x = pert_batch_internal_compound_enumerator, y = value, colour = pert_iname)) +
  geom_point()+
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free") + 
  labs(x = "Week",
       y = "GCP value",
       title = "PBS_0 and EGF_48 weekly variations",
       subtitle = "Raw data, y limits scaled to each probe value")
p

df <- GCP_z %>%
  filter(pert_time==0&pert_iname=="PBS"|pert_time==48&pert_iname=="EGF")

p <- ggplot(df, aes(x = pert_batch_internal_compound_enumerator, y = value_z, colour = pert_iname)) +
  geom_point()+
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free") + 
  labs(x = "Week",
       y = "GCP within week Z scores",
       title = "PBS_0 and EGF_48 weekly variations",
       subtitle = "Z scored data, y limits scaled to each probe value") +
    guides(colour = guide_legend(title = "Condition"))
p

p <- ggplot(df, aes(x = value, fill = pert_batch_internal_compound_enumerator)) + 
  geom_density(alpha = .2) +
  guides(fill = guide_legend(title = "Week")) +
  labs(x = "GCP value",
       title= "GCP values grouped by weeks",
       subtitle= "PBS_0 and EGF_48 conditions") +
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free")
p

p <- ggplot(df, aes(x = value_z, fill = pert_batch_internal_compound_enumerator)) + 
  geom_density(alpha = .2) +
  guides(fill = guide_legend(title = "Week")) +
  labs(x = "GCP z scores ",
         title= "GCP z scores grouped by weeks",
       subtitle= "PBS_0 and EGF_48 conditions") +
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free")
p

#Calculate z scores within replicate batches
df <- GCP_Data %>%
  select(matches("^H3K|_replicate|pert_iname|pert_time$")) %>%
  gather(key=probe_id, value = value, -pert_batch_internal_replicate,-pert_iname,-pert_time) %>%
  group_by(pert_batch_internal_replicate, probe_id) %>%
  mutate(value_z = z_score(value)) %>%
  ungroup() %>%
  filter(pert_time==0&pert_iname=="PBS"|pert_time==48&pert_iname=="EGF",
         pert_batch_internal_replicate %in% 1:3)

p <- ggplot(df, aes(x = value, fill = pert_batch_internal_replicate)) + 
  geom_density(alpha = .2) +
  guides(fill = FALSE) +
  labs(title= "GCP raw data grouped by replicate batches",
                subtitle= "PBS_0 and EGF_48 conditions") +
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free")
p

p <- ggplot(df, aes(x = value_z, fill = pert_batch_internal_replicate)) + 
  geom_density(alpha = .2) +
  labs(title= "GCP z scores within replicates",
                subtitle= "PBS_0 and EGF_48 conditions") +
  guides(fill = guide_legend(title = "Replicate")) +
  theme(strip.text = element_text(size = 8)) +
  facet_wrap(~probe_id, scales = "free")
p
```


```{r normalize, eval = FALSE}


EGF_values <- GCP_z %>%
  select(matches("^H3K|pert_batch_internal_compound_enumerator|pert_iname|pert_time$")) %>%
  filter(pert_iname == "EGF") %>%
  gather(probe_id,value,-pert_batch_internal_compound_enumerator,-pert_iname,-pert_time)

#identify the NA values
EGF_NAs <- EGF_values %>%
  filter(is.na(value)) %>%
  select(pert_iname, pert_time, probe_id, pert_batch_internal_replicate) 

#calculate the medians from the replicates of the NA values
EGF_imputed <- EGF_NAs %>%
  select(-pert_batch_internal_replicate) %>%
  left_join(EGF_values, by = c("pert_iname", "pert_time", "probe_id")) %>%
  distinct() %>%
  group_by(pert_iname, pert_time, probe_id) %>%
  summarise(value = median(value, na.rm = TRUE)) %>%
  ungroup() %>%
  right_join(EGF_NAs, by = c("pert_iname", "pert_time", "probe_id"))

#remove the NA values and add in the imputed values
EGF_values <- EGF_values %>%
  filter(!is.na(value)) %>%
  bind_rows(EGF_imputed) %>%
  rename(EGF_value = value) %>%
  select(-pert_iname)

#Add the EGF values and normalize to them
EGF_norm<- GCP_Data %>%
  filter(!pert_time == "0") %>%
  select(matches("^H3K|replicate|pert_iname|pert_time$")) %>%
  gather(probe_id,value,-pert_batch_internal_replicate,-pert_iname,-pert_time) %>%
  left_join(EGF_values, by = c("pert_time", "probe_id", "pert_batch_internal_replicate")) %>%
  mutate(value_EGF_norm = value-EGF_value) %>%
  select(-value, -EGF_value) %>%
  mutate(pert_iname = toupper(pert_iname),
         condition = paste(pert_iname, pert_time, pert_batch_internal_replicate, sep = "_"),
         probe_id = factor(probe_id, levels = unique(probe_id))) %>%
  spread(key = probe_id, value = value_EGF_norm) %>%
  mutate(condition =  factor(condition, levels = paste(rep(c("PBS","BMP2", "IFNG", "TGFB", "HGF", "OSM", "EGF"), each = 20), rep(c(4,8, 24, 48), each = 5), 1:5, sep = "_"))) %>%
  arrange(condition)

```

```{r perturbedConditions, fig.width = 4, fig.height=4, eval= FALSE}

df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time))

p <- ggplot(df, aes(x = Time, y = RPPA_fold_change_prop, colour = Ligand)) +
  geom_line() +
  labs(title = "RPPA fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies")
p

p <-ggplot(df, aes(x = Time, y = CycIF_fold_change_prop, colour = Ligand))+
  geom_line()+
  labs(title = "cycIF fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies")
p

p <- ggplot(df, aes(x = Time, y = GCP_fold_change_prop, colour = Ligand))+
  geom_line()+
  labs(title = "GCP fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed histones")
p

```

```{r perturbedConditionsZScores, fig.width = 3.5, fig.height=3.5, eval = FALSE}
pdf("signalEffectsColumns.pdf",width = 4, height = 4)
df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time)) %>%
  filter(!Ligand == "EGF")

# p <- ggplot(df, aes(x = Time, y = RPPA_Z_score_prop, colour = Ligand)) +
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line() +
#   labs(title = "RPPA signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed antibodies")
# p
# 
# p <-ggplot(df, aes(x = Time, y = CycIF_Z_score_prop, colour = Ligand))+
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line()+
#   labs(title = "cycIF signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed features")
# p
# 
# p <- ggplot(df, aes(x = Time, y = GCP_Z_score_prop, colour = Ligand))+
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line()+
#   labs(title = "GCP signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed histones")
# p


#Bar plots
p <- ggplot(df, aes(x = factor(Time), y = RPPA_Z_score_prop, fill = Ligand)) +
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "RPPA signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies") +
  theme_bw()
p

p <-ggplot(df, aes(x = factor(Time), y = CycIF_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "cycIF signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed features") +
  theme_bw()
p

p <- ggplot(df, aes(x = factor(Time), y = GCP_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "GCP signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed histones") +
  theme_bw()
p

p <- ggplot(df, aes(x = factor(Time), y = L1000_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "L1000 signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed genes") +
  theme_bw()
p

#line graphs grouped by ligand
df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time)) %>%
  select(Ligand, Time, matches("Z_score")) %>%
  gather(key = "Assay",value="Proportion",-Ligand, -Time) %>%
  mutate(Assay = str_remove(Assay,"_.*")) %>%
  filter(!Ligand == "EGF")

p <- ggplot(df, aes(x = Time, y = Proportion, colour = Assay)) +
  coord_cartesian(ylim = c(0,.45)) +
  geom_line() +
  scale_x_continuous(breaks = c(4,8,24,48)) +
  labs(title = "RPPA, cycIF, GCP and L1000 signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed features") +
  facet_wrap(~Ligand) +
  theme_bw()+
  theme(axis.text.x = element_text(size = 5))

p

```

```{r conditionTimeEGFNormT0Heatmap, eval=FALSE}
lowProb <- .02
upProb <- .98
m <- all_data %>%
  select(-Ligand_TimePoint) %>%
  unlist() %>%
  matrix(nrow = length(unique(all_data$Ligand_TimePoint)),byrow = TRUE) %>%
  squish(quantile(.,probs=c(lowProb, upProb), na.rm = TRUE)) 

rownames(m) <- all_data$Ligand_TimePoint
colnames(m) <- colnames(select(all_data, -Ligand_TimePoint))

ccols <- diverge.color(unlist(m), pal_choice = "RdBu", centeredOn = 0)

colAnBar <- all_data %>%
  select(-Ligand_TimePoint) %>%
  colnames() %>%
  str_remove("_.*")
colAnBar <- colAnBar %>%
  str_replace("cycIF", "blue") %>%
  str_replace("RPPA","pink") %>%
  str_replace("GCP","yellow")

#data with columns ordered by samples
hm <- heatmap(m,
              #Colv=NA,
              ColSideColors = colAnBar,
              scale="none",
              col=ccols[[2]][length(ccols[[2]]):1],
              breaks=ccols[[1]]$brks,
              margins = c(5,10),
              cexRow = .8,
              cexCol = .8)


```


