---
title: "MDD standard figures"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE,  message=FALSE, warning = FALSE, fig.height=10, fig.width=10)

suppressMessages(library(tidyverse))
suppressMessages(library(ComplexHeatmap))
library(umap)

```


## Overview{.tabset .tabset-fade}
These figures are derived from the level 4 data downloaded from the LINCS Molecular Deep Dive files on Synapse https://www.synapse.org/#!Synapse:syn2862345/wiki/588244.  



```{r standardFigureFunctions}

#' Read an assay's csv or tsv data file 
load_data <- function(assay_name, level = 4){
  file_name <- dir(pattern = paste0("MDD_", assay_name,"_","Level",level,".csv"),recursive = TRUE, full.names = TRUE)
  if(!length(file_name) == 1) stop("There was not one ", assay_name, " data file found")
    
  if(str_detect(file_name, "csv")) {
    df <- read_csv(file_name)
  } else if (str_detect(file_name, "tsv")){
    df <- read_tsv(file_name)
  } else stop("The data file ",file_name, " must be a csv or tsv file type")
} #end of function

get_win_probs <- function(df, low = .02, hi = .98){
  windsorize_probs <- df %>%
    dplyr::select(-feature) %>%
    unlist %>%
    quantile(probs = c(low, hi), na.rm = TRUE)
}
  
prep_data <- function(df, md){
    df <- df %>%
    gather(specimenID, value, -feature) %>%
    inner_join(md, by = "specimenID") %>%
    dplyr::select(feature, specimenName, value) %>%
    spread(specimenName, value) %>%
    mutate(feature = factor(feature, levels = unique(df$feature))) %>%
      arrange(feature,)
  #Set the order of the columns
  condition_order <-  paste(rep(c("ctrl","PBS", "HGF", "OSM", "EGF","BMP2", "IFNG", "TGFB"), each = 30, times = 3), rep(c(0, 1, 4 ,8, 24, 48), each = 5, times = 3), rep(c("C1", "C2", "C3"), each = 240), rep(c("A", "B", "C", "D", "E"), times = 109),  sep = "_") %>%
    intersect(colnames(df))
  
  #Arrange columns by standard condition order
  df <- df %>%
    dplyr::select(feature, condition_order)
  return(df)
}

prep_annotations <- function(df, md){
      df_ann <- df %>%
      gather("specimenName", "value", -feature) %>%
      inner_join(md, by = "specimenName") %>%
      dplyr::select(ligand, secondLigand, experimentalTimePoint, replicate, collection) %>%
      distinct() %>%
      rename(Time = experimentalTimePoint,
             Ligand = ligand,
             Ligand2 = secondLigand,
             Replicate = replicate,
             Collection = collection) %>%
      as.data.frame()
      return(df_ann)
}
 #Create the heatmap column annotations
create_top_annotations <- function(df, md){
  df_ann <- prep_annotations(df, md)
  haTop <- HeatmapAnnotation(df = df_ann,
                             col = list(Ligand = c("ctrl" = "#7A4A2A",
                                                   "PBS" = "#8dd3c7",
                                                    "HGF" = "#80b1d3",
                                                    "OSM" = "#fdb462",
                                                    "EGF" = "#fb8072",
                                                    "BMP2" = "#b3de69",
                                                    "IFNG" = "#bebada",
                                                    "TGFB" = "#ffd92f"),
                                        Time = c("0" = "white", "1" = "azure1", "4" = "azure2", "8" = "azure3", "24" = "azure4", "48" = "black"), 
                                        Ligand2 = c("EGF" = "#9E79A3", "none" = "#BE7249"),
                                        Replicate = c("A" = '#80b1d3',"B" = '#fdb462',"C" = '#ffd92f',"D" = '#8dd3c7',"E" = '#bebada'),
                                        Collection = c("C1" = "#D79FD4", "C2" = "#3CC3B9", "C3" = "#B9B34C")))
  return(haTop)
}

prep_top_annotations <- function(df, md){
  df_ann <- prep_annotations(df, md)
  haTop <- HeatmapAnnotation(df = df_ann,
                             col = list(Ligand = c("ctrl" = "#7A4A2A",
                                                   "PBS" = "#8dd3c7",
                                                    "HGF" = "#80b1d3",
                                                    "OSM" = "#fdb462",
                                                    "EGF" = "#fb8072",
                                                    "BMP2" = "#b3de69",
                                                    "IFNG" = "#bebada",
                                                    "TGFB" = "#ffd92f"),
                                        Time = c("0" = "white", "1" = "azure1", "4" = "azure2", "8" = "azure3", "24" = "azure4", "48" = "black"), 
                                        Ligand2 = c("EGF" = "#9E79A3", "none" = "#BE7249"),
                                        Replicate = c("A" = '#80b1d3',"B" = '#fdb462',"C" = '#ffd92f',"D" = '#8dd3c7',"E" = '#bebada'),
                                        Collection = c("C1" = "#D79FD4", "C2" = "#3CC3B9", "C3" = "#B9B34C")))
  return(haTop)
}

create_row_annotations <- function(df, md){
  df_ann <- prep_annotations(df, md) %>%
    dplyr::select(Collection, Replicate, Time, Ligand2, Ligand)
  haRow <- rowAnnotation(df = df_ann, show_legend = FALSE,
                             col = list(Ligand = c( "ctrl" = "#7A4A2A",
                                                    "PBS" = "#8dd3c7",
                                                    "HGF" = "#80b1d3",
                                                    "OSM" = "#fdb462",
                                                    "EGF" = "#fb8072",
                                                    "BMP2" = "#b3de69",
                                                    "IFNG" = "#bebada",
                                                    "TGFB" = "#ffd92f"),
                                        Time = c("0" = "white", "1" = "azure1", "4" = "azure2", "8" = "azure3", "24" = "azure4", "48" = "black"), 
                                        Ligand2 = c("EGF" = "#9E79A3", "none" = "#BE7249"),
                                        Replicate = c("A" = '#80b1d3',"B" = '#fdb462',"C" = '#ffd92f',"D" = '#8dd3c7',"E" = '#bebada'),
                                        Collection = c("C1" = "#D79FD4", "C2" = "#3CC3B9", "C3" = "#B9B34C")))
  return(haRow)
}

  

##########
```

```{r globalVariables}
ligand_cols <- c("ctrl" = "#7A4A2A",
                 "PBS" = "#8dd3c7",
                  "HGF" = "#80b1d3",
                  "OSM" = "#fdb462",
                  "EGF" = "#fb8072",
                  "BMP2" = "#b3de69",
                  "IFNG" = "#bebada",
                  "TGFB" = "#ffd92f")

ligand_2_cols = c("EGF" = "#ff0000",
                     "None" = "#00000000")

md <- read_csv("metadata/MDD_sample_annotations.csv")
```


```{r rppa_figures}

RPPA_l1 <- load_data(assay_name = "RPPA", level = 1) %>%
  rename(feature = antibody) %>%
  gather(key = specimenID, value = value, -feature) %>%
  group_by(feature) %>%
  mutate(value = value - median(value, na.rm = TRUE)) %>%
  ungroup() %>%
    spread(key = specimenID, value = value)

```


#### Line graphs

```{r, fig.height=4, fig.width=15}

df <- RPPA_l1 %>%
  filter(feature %in% c("c-Myc", "Cyclin-D1", "Cyclin-B1", "p21", "Akt_pS473", "Akt_pT308","MAPK_pT202_Y204"))
fc_thresh = 0


  windsorize_probs <- get_win_probs(df, .01, .99)
  
  df_sum <- df %>%
    prep_data(md = md) %>%
    gather("specimenName", "value", -feature) %>%
    inner_join(md, by = "specimenName") %>%
    dplyr::select(ligand, secondLigand, experimentalTimePoint, replicate, collection, feature, value) %>%
    rename(Time = experimentalTimePoint,
           Ligand = ligand,
           Ligand2 = secondLigand,
           Replicate = replicate,
           Collection = collection) %>%
    group_by(feature, Collection, Time, Ligand) %>%
    summarise(value = median(value)) %>%
    ungroup() %>%
    filter(Ligand %in% c("EGF", "IFNG","TGFB"))
  
  if(0 %in% unique(df_sum$Time)){
    df2 <- df_sum %>%
      filter(Time == 0) %>%
      data.frame(Ligand = rep(unique(df_sum$Ligand), each = length(unique(df_sum$feature))),
                 stringsAsFactors = FALSE) %>%
      dplyr::select(feature, Ligand.1, value, Collection, Time) %>%
      rename(Ligand = Ligand.1) %>%
      bind_rows(df_sum) %>%
      filter(!Ligand == "ctrl") 
  } else {
    df2 <- df_sum
  }
  
  
  fc_set <- df2 %>%
    group_by(Time, Ligand) %>%
    filter(abs(value) > fc_thresh) %>%
    ungroup() %>%
    dplyr::select(feature) %>%
    distinct() %>%
    inner_join(df2, by = "feature") %>%
    mutate(Ligand = factor(Ligand, levels = names(ligand_cols)))
  
  title_suffix <- ""
 
  p <- ggplot(fc_set, aes(x=Time, y=value, colour=Ligand))+
    geom_line(size = 2)+
    labs(x = "Time (hours)",
         y="Intensity (AU)") +
    scale_x_continuous(breaks = c(0,8,24,48)) +
    scale_color_manual(values = ligand_cols) +
    theme(axis.text.x = element_text(angle=90),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          strip.text = element_text(size=10, hjust=0),
            panel.background = element_rect(fill = NA),
  panel.grid.major = element_line(colour = "gray95"))+
    facet_wrap(~feature, ncol = 10,scales = "free_y")
  p
  
 
  p <- ggplot(fc_set, aes(x=Time, y=value, colour=Ligand))+
    geom_line(size = 2)+
    labs(title=paste0("Line Graphs",title_suffix),
         x = "Time (hours)",
         y="Intensity (AU)") +
    scale_x_continuous(breaks = c(0,8,24,48)) +
    scale_color_manual(values = ligand_cols) +
    theme(axis.text.x = element_text(angle=90),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          strip.text = element_text(size=10, hjust=0),
            panel.background = element_rect(fill = NA),
  panel.grid.major = element_line(colour = "gray95"))+
    facet_wrap(~feature, ncol = 10)
  p
  
```

