---
title: "Analysis of neutrophil elastase in MDD integrated modules"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE, fig.height=10, fig.width=12)

suppressMessages(library(tidyverse))
library(ComplexHeatmap)
library(circlize)

```

Filter the median-summarized lfc MDD data to cathepsin B(CTSB), cathepsin C(CTSC), neutrophil elastase(ELANE), MMP-9(MMP9) and MMP-14(MMP14).  
Normalize to time 0 by subtracting the ctrl_0 lfc values.  
 

```{r MDD_ne_genes}

#make a list with a character vector of gene names from each module
ligand_order <-  c("ctrl", "PBS", "HGF", "OSM", "EGF","BMP2", "IFNG", "TGFB")
condition_order <- paste0(rep(ligand_order, each = 3), rep(c("_0", "_24", "_48"), times = length(ligand_order)))

ne_genes <- c("CTSB","CTSC","ELANE","MMP9","MMP14")
file_name <- "../RNAseq/Data/MDD_RNAseq_med.csv"
mdd_RNAseq_ne <- read_csv(file_name) %>%
  filter(feature %in% ne_genes) %>%
   pivot_wider(names_from = condition, values_from = value) %>%
  select(feature, matches(condition_order))

ne_dm <- mdd_RNAseq_ne %>%
   dplyr::select(where(is.numeric)) %>%
  as.matrix 
rownames(ne_dm) <- mdd_RNAseq_ne$feature

mdd_RNAseq_ne_T0 <- mdd_RNAseq_ne %>%
mutate(across(where(is.numeric),  ~.x - ctrl_0))

ne_dm_T0 <- mdd_RNAseq_ne_T0 %>%
   dplyr::select(where(is.numeric)) %>%
  as.matrix 
rownames(ne_dm_T0) <- mdd_RNAseq_ne_T0$feature

```


```{r create_heatmaps, fig.width=4, fig.height=4}

hm_ne <- Heatmap(ne_dm,
                       name = "lfc",
                       column_title = "neutrophil elastase in MDD RNAseq",
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 7),
                       column_names_gp = gpar(fontsize = 7),
                       use_raster = FALSE)
hm_ne

write_csv(as.data.frame(ne_dm) %>%
  mutate(gene = rownames(ne_dm)) %>%
  select(gene, everything()), "../tables/MDD_RNAseq_ne.csv")


#Simple T0 normalized
hm_ne_T0_lfc <- Heatmap(ne_dm_T0,
                       name = "lfc",
                       column_title = "neutrophil elastase in MDD RNAseq\n (simple T0 normalized)",
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 7),
                       column_names_gp = gpar(fontsize = 7),
                       use_raster = FALSE)
hm_ne_T0_lfc

write_csv(mdd_RNAseq_ne_T0, "../tables/MDD_RNAseq_ne_T0.csv")
```
