---
title: "`r FEATURENAME` CHEA3 Enrichment Binary Heatmaps"
author: "Daniel Derrick"
date: "9/30/2020"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    df_print: paged
  html_notebook:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup0, include=FALSE}
library(tidyverse)
library(ComplexHeatmap)
library(DT)
```

This script is for binary heatmaps of TF enrichments from `r FEATURENAME`.

# Summary of significant TFs per module

```{r}
CHEA3_in %>% 
  filter(significant) %>% 
  dplyr::select(TF, Module, significant) %>%
  group_by(Module) %>% 
  summarize(n = n())

sigTFs <- 
  CHEA3_in %>% 
  filter(significant) %>% 
  pull(TF) %>% 
  unique()
```

```{r, fig.height = 10}
# setup for figs
colDirection = c(Significant = "red", 
                 background = "gray80")

posNegW <- .95
posNegH <- .9
grayW <- .95
grayH <- .8
edgeCol <- NA

aFun <- list(
  background = function(x, y, w, h) {
    grid.rect(x, y, w*grayW, h*grayH,
              gp = gpar(fill = colDirection["background"],
                        col = edgeCol))
    },
    Significant = function(x, y, w, h) {
      grid.rect(x, y, w*posNegW, h*posNegH,
                gp = gpar(fill = colDirection["Significant"],
                          col = edgeCol))
    }
)
```

# Binary Heatmap: Top 5 TFs per condition

```{r, fig.height = 7}
n <- 5
sigTFs_top <- 
  CHEA3_in %>% 
  filter(significant) %>% 
  filter(Rank <= n) %>% 
  pull(TF) %>% 
  unique

topPlot <-
  CHEA3_in %>% 
  filter(TF %in% sigTFs_top) %>%
  dplyr::select(TF, Module, significant) %>%
  mutate(significant = case_when(significant ~ "Significant",
                           !significant ~ "")) %>% 
  # dplyr::select(-significant) %>% 
  pivot_wider(names_from = "Module", values_from = "significant") %>%
  column_to_rownames("TF") %>% 
  as.matrix %>% 
  oncoPrint(show_column_names = TRUE,
            alter_fun = aFun,
            column_order = colnames(.),
            col = colDirection,
            heatmap_legend_param = list(title = "Enrichment"))

topPlot

pdf(sprintf("%s/MDD_%s_binaryHeatmap_top%s.pdf", outDir, FEATURE, n), height = 7)
topPlot
dev.off()
```

# Binary Heatmap: Top 10 TFs per condition

```{r, fig.height = 10}
n <- 10
sigTFs_top <- 
  CHEA3_in %>% 
  filter(significant) %>% 
  filter(Rank <= n) %>% 
  pull(TF) %>% 
  unique

topPlot <-
  CHEA3_in %>% 
  filter(TF %in% sigTFs_top) %>%
  dplyr::select(TF, Module, significant) %>%
  mutate(significant = case_when(significant ~ "Significant",
                           !significant ~ "")) %>% 
  # dplyr::select(-significant) %>% 
  pivot_wider(names_from = "Module", values_from = "significant") %>%
  column_to_rownames("TF") %>% 
  as.matrix %>% 
  oncoPrint(show_column_names = TRUE,
            alter_fun = aFun,
            column_order = colnames(.),
            col = colDirection,
            heatmap_legend_param = list(title = "Enrichment"))

topPlot

pdf(sprintf("%s/MDD_%s_binaryHeatmap_top%s.pdf", outDir, FEATURE, n), height = 10)
topPlot
dev.off()
```


# Binary Heatmap: Top 20 TFs per condition

```{r, fig.height = 18}
n <- 20
sigTFs_top <- 
  CHEA3_in %>% 
  filter(significant) %>% 
  filter(Rank <= n) %>% 
  pull(TF) %>% 
  unique

topPlot <-
  CHEA3_in %>% 
  filter(TF %in% sigTFs_top) %>%
  dplyr::select(TF, Module, significant) %>%
  mutate(significant = case_when(significant ~ "Significant",
                           !significant ~ "")) %>% 
  # dplyr::select(-significant) %>% 
  pivot_wider(names_from = "Module", values_from = "significant") %>%
  column_to_rownames("TF") %>% 
  as.matrix %>% 
  oncoPrint(show_column_names = TRUE,
            alter_fun = aFun,
            column_order = colnames(.),
            col = colDirection,
            heatmap_legend_param = list(title = "Enrichment"))

topPlot

pdf(sprintf("%s/MDD_%s_binaryHeatmap_top%s.pdf", outDir, FEATURE, n), height = 18)
topPlot
dev.off()
```

# Binary Heatmap: All Significant

```{r, fig.height = 40}
sigTFs_top <- 
  CHEA3_in %>% 
  filter(significant) %>% 
  pull(TF) %>% 
  unique

topPlot <-
  CHEA3_in %>% 
  filter(TF %in% sigTFs_top) %>%
  dplyr::select(TF, Module, significant) %>%
  mutate(significant = case_when(significant ~ "Significant",
                           !significant ~ "")) %>% 
  # dplyr::select(-significant) %>% 
  pivot_wider(names_from = "Module", values_from = "significant") %>%
  column_to_rownames("TF") %>% 
  as.matrix %>% 
  oncoPrint(show_column_names = TRUE,
            alter_fun = aFun,
            column_order = colnames(.),
            col = colDirection,
            heatmap_legend_param = list(title = "Enrichment"))

topPlot

pdf(sprintf("%s/MDD_%s_binaryHeatmap_top%s.pdf", outDir, FEATURE, n), height = 40)
topPlot
dev.off()
```
