---
title: "MDD integrated analysis, compare PBS to noPBS2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE, fig.height=10, fig.width=14)

suppressMessages(library(tidyverse))
library(readxl)

```


```{r prepData}

#Read in the integrated data with PBS
all_features_data_PBS <- read_csv("../MDD_all_features_data_PBS.csv") %>%   filter(Type == "RNAseq")
#   group_by(feature) %>% #average data annotated with the same gene
# summarise(across(.cols = where(is.numeric), .fns = mean)) %>%
#   ungroup()

# #get data from one module in the excel file
 get_data_from_excel <- function(sheet_name, file_name){
     genes <- read_excel(file_name, sheet = sheet_name) %>%
    filter(Type == "RNAseq") %>%
       mutate(module = sheet_name)
     if(nrow(genes) == 0) return(NULL)
     return(genes)
 }
 
 #Get the data from all sheets of the noPBS2 combined data file
file_name <- "MDD_int_rr_combined_tables.xlsx"
combined_data_noPBS <- map(excel_sheets(file_name), get_data_from_excel, file_name = file_name) %>%
  bind_rows()

#format PBS data to match noPBS data
PBS_data <- all_features_data_PBS %>%
  select(matches(colnames(combined_data_noPBS))) %>%
  filter(feature %in% combined_data_noPBS$feature) %>%
  mutate(PBS_status = "with_PBS")

#format no PBS data to match PBS data
noPBS_data <- combined_data_noPBS %>%
  mutate(PBS_status = "no_PBS") %>%
   select(all_of(colnames(PBS_data)))

all_data <- bind_rows(PBS_data, noPBS_data)

#reformat to have columns value_PBS, value_noPBS
all_data_correlated <- all_data %>%
  pivot_longer(cols = where(is.numeric), names_to = "condition") %>%
  pivot_wider(names_from = PBS_status, values_from = value) %>%
  group_by(feature) %>%
  summarise(correlation = cor(no_PBS, with_PBS)) %>%
  ungroup()

```

```{r visualize_correlations}

p <- ggplot(all_data_correlated, aes(x = correlation)) +
  geom_histogram(bins = 200) +
  coord_cartesian(xlim = c(.95, 1))
p

p <- ggplot(all_data_correlated, aes(x = correlation)) +
  geom_density()
p



```




