---
title: LINCS molecular deep dive timecourse analysis
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE,  message=FALSE, warning = FALSE, fig.height=10, fig.width=10)

library(scales)
library(RColorBrewer)
library(MDDRPPA)
library(classInt)
library(tidyverse)

```

```{r functions}

diverge.color <- function(data,pal_choice="RdGy",centeredOn=0){
  nHalf=50
  Min <- min(data,na.rm=TRUE)
  Max <- max(data,na.rm=TRUE)
  Thresh <- centeredOn
  pal<-brewer.pal(n=11,pal_choice)
  rc1<-colorRampPalette(colors=c(pal[1],pal[2]),space="Lab")(10)
  for(i in 2:10){
    tmp<-colorRampPalette(colors=c(pal[i],pal[i+1]),space="Lab")(10)
    rc1<-c(rc1,tmp)
  }
  rb1 <- seq(Min, Thresh, length.out=nHalf+1)
  rb2 <- seq(Thresh, Max, length.out=nHalf+1)[-1]
  rampbreaks <- c(rb1, rb2)
  cuts <- classIntervals(data, style="fixed",fixedBreaks=rampbreaks)
  return(list(cuts,rc1))
}

#Add the ctrl values as time 0 for every Biomarker
#T0Norm will all have value = 1
#For each Biomarker and ligand , get the timepoint 1 values
#replace the T0Norm value with 1, replace the timepoint with 0
addCtrlT0Norm <- function(df){
  dfT0 <- lapply(unique(df$Ligand), function(ligand){
    df %>%
      filter(TimePoint==0) %>%
      mutate(Ligand=ligand)
  }) %>%
    bind_rows() %>%
    filter(!Ligand=="ctrl") %>%
    bind_rows(df) %>%
    mutate(Ligand_TimePoint=paste0(Ligand,"_",TimePoint)) %>%
    filter(!Ligand=="ctrl")
}


####global parameters
cols <- brewer.pal(9,"OrRd")
spectralPal <- brewer.pal(11,"Spectral")
blRdPal <- brewer.pal(11,"RdBu")[11:1]


#Values used for out of bounds values
lowProb <- .02
upProb <- .98

#Filter threshold for Biomarker variances
varianceCut <- 0.04

#fold change threshold
fcThresh <- 1.5
z_score_thresh <- 1.5

#Create a function that takes in a vector and returns a same-length vector of z scores 
z_score <- function(x) (x-mean(x, na.rm = TRUE))/sqrt(var(x, na.rm = TRUE))

```


```{r getData}

cycIF<- read_csv("../cycIF/Data/MDD_cycIF_level_4.csv") %>%
  rename(Ligand_TimePoint =ConditionDescription) %>%
  select(Ligand_TimePoint, Intensity_EGFnorm, Biomarker) %>%
  mutate(Biomarker = paste0("cycIF_", Biomarker)) %>%
  spread(key = Biomarker, value = Intensity_EGFnorm)

#Count number of features with abs value above the fc threshold
fc_logicals <- abs(select(cycIF,-Ligand_TimePoint)) >= log2(fcThresh)
#Add the proportion of perturbed features to the dataframe
cycIF$CycIF_fold_change_prop <- apply(fc_logicals, 1, sum, na.rm = TRUE)/ncol(fc_logicals)

cycIF_zscores <- cycIF %>%
  mutate_at(vars(-matches("Ligand|fold_change")), z_score)
zs_logicals <-  abs(select(cycIF_zscores,-Ligand_TimePoint)) >= z_score_thresh

#Add the proportion of perturbed antibodies to the dataframe based on z scores
cycIF$CycIF_Z_score_prop <- apply(zs_logicals, 1, sum, na.rm = TRUE)/ncol(zs_logicals)


#Load level 3 data
RPPA <- read_tsv("../MDDRPPA/MDD_RPPA_Mean_Level3.tsv",
                 col_types =  cols(
                   `Slide no.` = col_integer(),
                   Value = col_double(),
                   T0Norm = col_double(),
                   TCNorm = col_double(),
                   PBSNorm = col_double(),
                   EGFNorm = col_double(),
                   RTK = col_logical(),
                   cycIF = col_logical(),
                   Fig1 = col_logical(),
                   Histone = col_logical(),
                   CellCycle = col_logical()
                 )) %>%
  select(Ligand_TimePoint, EGFNorm, Antibody) %>%
  mutate(Antibody = paste0("RPPA_",Antibody)) %>%
  spread(key = Antibody, value = EGFNorm) %>%
  mutate_if(is.numeric, log2)

#Count number of antibodies with abs value above the fc threshold
fc_logicals <- abs(select(RPPA,-Ligand_TimePoint)) >= log2(fcThresh)
#Add the proportion of perturbed antibodies to the dataframe
RPPA$RPPA_fold_change_prop <- apply(fc_logicals, 1, sum, na.rm = TRUE)/ncol(fc_logicals)

RPPA_zscores <- RPPA %>%
  mutate_at(vars(-matches("Ligand|fold_change")), z_score)
zs_logicals <-  abs(select(RPPA_zscores,-Ligand_TimePoint)) >= z_score_thresh

#Add the proportion of perturbed antibodies to the dataframe based on z scores
RPPA$RPPA_Z_score_prop <- apply(zs_logicals, 1, sum, na.rm = TRUE)/ncol(zs_logicals)

GCP_metadata <- read_csv("MCF10a_GCP_data_with_OHSU_metadata_vocabulary.csv") %>%
  select(-contains("GMa")) %>%
  slice(-1:-23)

GCP_data <- read_csv("MCF10a_GCP_data_with_OHSU_metadata_vocabulary.csv") %>%
  select(matches("GMa|^id")) %>%
  gather(sample_id,valname,-id) %>%
  spread(id,valname) %>%
  select(matches("BI|condition")) %>%
  rename(Ligand_TimePoint = condition) %>%
  mutate_at(vars(matches("BI")), as.numeric) %>%
  group_by(Ligand_TimePoint) %>%
  summarise_all(mean) %>%
  ungroup() %>%
  gather(histone, val,-Ligand_TimePoint) %>%
  mutate(histone = paste0("GCP_",histone)) %>%
  spread(histone, val)

#Count number of histones with abs value above the fc threshold
fc_logicals <- abs(select(GCP_data,-Ligand_TimePoint)) >= log2(fcThresh)
#Add the proportion of perturbed features to the dataframe
GCP_data$GCP_fold_change_prop <- apply(fc_logicals, 1, sum, na.rm = TRUE)/ncol(fc_logicals)

GCP_zscores <- GCP_data %>%
  mutate_at(vars(-matches("Ligand|fold_change")), z_score)
zs_logicals <-  abs(select(GCP_zscores,-Ligand_TimePoint)) >= z_score_thresh

#Add the proportion of perturbed antibodies to the dataframe based on z scores
GCP_data$GCP_Z_score_prop <- apply(zs_logicals, 1, sum, na.rm = TRUE)/ncol(zs_logicals)

#Add L1000 data
l1000_data <- read_tsv("MCF10A_L1000_TCnorm.tsv") %>%
  gather(Ligand_TimePoint_Replicate, Value, -probe) %>%
  mutate(Ligand_TimePoint = str_remove(Ligand_TimePoint_Replicate, "_[ABC]"),
         probe = paste0("L1000_",probe)) %>%
  group_by(Ligand_TimePoint, probe) %>%
  summarise(Value = mean(Value)) %>%
  spread(probe, Value) %>%
  ungroup()
  
l1000_zscores <- l1000_data %>%
  mutate_at(vars(-matches("Ligand_TimePoint")), z_score)
zs_logicals <-  abs(select(l1000_zscores,-Ligand_TimePoint)) >= z_score_thresh

#Add the proportion of perturbed antibodies to the dataframe based on z scores
l1000_data$L1000_Z_score_prop <- apply(zs_logicals, 1, sum, na.rm = TRUE)/ncol(zs_logicals)

#l1000_metadata <- read_tsv("MCF10A_L1000_TCnorm_meta.tsv")

#join all data
all_data <- inner_join(cycIF,RPPA) %>%
  inner_join(GCP_data) %>%
  inner_join(l1000_data) %>%
  arrange(Ligand_TimePoint)

all_data$Ligand_TimePoint <- factor(all_data$Ligand_TimePoint, levels = c(
  "BMP2_1","BMP2_4","BMP2_8","BMP2_24","BMP2_48",
  "IFNG_1","IFNG_4","IFNG_8","IFNG_24","IFNG_48",
  "TGFB_1","TGFB_4","TGFB_8","TGFB_24","TGFB_48",
  "HGF_1","HGF_4","HGF_8","HGF_24","HGF_48",
  "OSM_1","OSM_4","OSM_8","OSM_24","OSM_48",
  "EGF_1","EGF_4","EGF_8","EGF_24","EGF_48"))


```

```{r distributions, eval = FALSE}
pdf("MDD_value_distributions.pdf")
df <- cycIF %>%
  gather(key=Ligand_TimePoint)
p <- ggplot(df, aes(x = value, fill = Ligand_TimePoint)) + 
  geom_density(alpha = .2) +
  guides(fill = FALSE) +
  labs(title= "cycIF")
p

df <- RPPA %>%
  gather(key=Ligand_TimePoint)
p <- ggplot(df, aes(x = value, fill = Ligand_TimePoint)) + 
  geom_density(alpha = .2) +
  guides(fill = FALSE)+
  labs(title= "RPPA")
p

df <- GCP_data %>%
  gather(key=Ligand_TimePoint)
p <- ggplot(df, aes(x = value, fill = Ligand_TimePoint)) + 
  geom_density(alpha = .2) +
  guides(fill = FALSE)+
  labs(title= "GCP")
p

df <- l1000_data %>%
  gather(key=Ligand_TimePoint)
p <- ggplot(df, aes(x = value, fill = Ligand_TimePoint)) + 
  geom_density(alpha = .2) +
  guides(fill = FALSE)+
  labs(title= "L1000")
p

dev.off()
```

```{r perturbedConditions, fig.width = 4, fig.height=4, eval= FALSE}

df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time))

p <- ggplot(df, aes(x = Time, y = RPPA_fold_change_prop, colour = Ligand)) +
  geom_line() +
  labs(title = "RPPA fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies")
p

p <-ggplot(df, aes(x = Time, y = CycIF_fold_change_prop, colour = Ligand))+
  geom_line()+
  labs(title = "cycIF fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies")
p

p <- ggplot(df, aes(x = Time, y = GCP_fold_change_prop, colour = Ligand))+
  geom_line()+
  labs(title = "GCP fold change proportions",
       subtitle = paste("fc threshold =",fcThresh),
       x = "Hours",
       y = "Proportion of perturbed histones")
p

```

```{r perturbedConditionsZScores, fig.width = 3.5, fig.height=3.5}
pdf("signalEffectsColumns.pdf",width = 4, height = 4)
df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time)) %>%
  filter(!Ligand == "EGF")

# p <- ggplot(df, aes(x = Time, y = RPPA_Z_score_prop, colour = Ligand)) +
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line() +
#   labs(title = "RPPA signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed antibodies")
# p
# 
# p <-ggplot(df, aes(x = Time, y = CycIF_Z_score_prop, colour = Ligand))+
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line()+
#   labs(title = "cycIF signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed features")
# p
# 
# p <- ggplot(df, aes(x = Time, y = GCP_Z_score_prop, colour = Ligand))+
#   coord_cartesian(ylim = c(0,.45)) +
#   geom_line()+
#   labs(title = "GCP signal effects",
#        subtitle = paste("z score threshold =", z_score_thresh),
#        x = "Hours",
#        y = "Proportion of perturbed histones")
# p


#Bar plots
p <- ggplot(df, aes(x = factor(Time), y = RPPA_Z_score_prop, fill = Ligand)) +
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "RPPA signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed antibodies") +
  theme_bw()
p

p <-ggplot(df, aes(x = factor(Time), y = CycIF_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "cycIF signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed features") +
  theme_bw()
p

p <- ggplot(df, aes(x = factor(Time), y = GCP_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "GCP signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed histones") +
  theme_bw()
p

p <- ggplot(df, aes(x = factor(Time), y = L1000_Z_score_prop, fill = Ligand))+
  coord_cartesian(ylim = c(0,.45)) +
  geom_col(position = "dodge", width=.8) +
  labs(title = "L1000 signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed genes") +
  theme_bw()
p

#line graphs grouped by ligand
df <- all_data %>%
  mutate(Ligand = str_remove(Ligand_TimePoint, "_.*"),
         Time = str_remove(Ligand_TimePoint, ".*_"),
         Time = as.integer(Time)) %>%
  select(Ligand, Time, matches("Z_score")) %>%
  gather(key = "Assay",value="Proportion",-Ligand, -Time) %>%
  mutate(Assay = str_remove(Assay,"_.*")) %>%
  filter(!Ligand == "EGF")

p <- ggplot(df, aes(x = Time, y = Proportion, colour = Assay)) +
  coord_cartesian(ylim = c(0,.45)) +
  geom_line() +
  scale_x_continuous(breaks = c(4,8,24,48)) +
  labs(title = "RPPA, cycIF, GCP and L1000 signal effects",
       subtitle = paste("z score threshold =", z_score_thresh),
       x = "Hours",
       y = "Proportion of perturbed features") +
  facet_wrap(~Ligand) +
  theme_bw()+
  theme(axis.text.x = element_text(size = 5))

p

 dev.off()
```

```{r conditionTimeEGFNormT0Heatmap, eval=FALSE}
lowProb <- .02
upProb <- .98
m <- all_data %>%
  select(-Ligand_TimePoint) %>%
  unlist() %>%
  matrix(nrow = length(unique(all_data$Ligand_TimePoint)),byrow = TRUE) %>%
  squish(quantile(.,probs=c(lowProb, upProb), na.rm = TRUE)) 

rownames(m) <- all_data$Ligand_TimePoint
colnames(m) <- colnames(select(all_data, -Ligand_TimePoint))

ccols <- diverge.color(unlist(m), pal_choice = "RdBu", centeredOn = 0)

colAnBar <- all_data %>%
  select(-Ligand_TimePoint) %>%
  colnames() %>%
  str_remove("_.*")
colAnBar <- colAnBar %>%
  str_replace("cycIF", "blue") %>%
  str_replace("RPPA","pink") %>%
  str_replace("GCP","yellow")

#data with columns ordered by samples
hm <- heatmap(m,
              #Colv=NA,
              ColSideColors = colAnBar,
              scale="none",
              col=ccols[[2]][length(ccols[[2]]):1],
              breaks=ccols[[1]]$brks,
              margins = c(5,10),
              cexRow = .8,
              cexCol = .8)


```


