---
title: "Analysis of Reactome GSEA in MDD RNAseq data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE, fig.height=10, fig.width=12)

suppressMessages(library(tidyverse))
library(ComplexHeatmap)
library(circlize)
library(writexl)

```

#### METHOD  
Perform GSEA on the ligand vs T0 MDD RNA seq data
Use the normalized Enrichment Score (NES) to compare the Reactome gene sets in the ligand responses  



```{r MDD_data}

#make a list with a character vector of gene names from each module
ligands <- c("PBS", "HGF", "OSM", "EGF","BMP2", "IFNG", "TGFB")
ligand_order <-  c("ctrl", ligands)
condition_order <- paste0(ligand_order, c("_0", rep("_24", times = 7)))

#Read in GSEA tables
data_path <- "~/gsea_home/output/jan13_Reactome/"

ligand_uids <- dir(data_path,
                   pattern = "gsea_report_for_.*.tsv",
                   recursive = TRUE) %>%
  str_extract("_[[:digit:]]*.tsv") %>%
  str_extract("_[[:digit:]]*") %>%
  str_remove("_") %>%
  unique()

GSEA_files <- dir(data_path,
                  pattern = "gsea_report_for_.*.tsv",
                  recursive = TRUE,
                  full.names = TRUE) 

Reactome_all <- map(ligand_uids, .f = function(uid){
  file_names <- dir(data_path,
                    pattern = paste0("gsea_report.*",uid, ".tsv"),
                   recursive = TRUE,
                   full.names = TRUE)
  ligand <- str_extract(file_names, str_c(ligands, collapse = "|")) %>% na.omit
  ligand_data <- map(file_names,  read_tsv) %>%
    bind_rows() %>%
    janitor::clean_names() %>%
    mutate(ligand = ligand)

  return(ligand_data)
  }) %>%
  bind_rows() 

Reactome <- Reactome_all %>%
     select(name, ligand, nes)%>%
  pivot_wider(names_from = ligand, values_from = nes)

Reactome_dm <- Reactome %>%
  select(-name) %>%
  as.matrix()
rownames(Reactome_dm) <- Reactome$name
#what would the reactome gsea heatmap look like if you remove all pathways/genesets that did not have a significant q-value (<0.25) in at least one ligand
fdr_q_thresh <- 0.25

Reactome_sig <- Reactome_all %>%
  filter(fdr_q_val <= fdr_q_thresh) %>%
  select(name) %>%
  distinct() %>%
  left_join(Reactome_all, by = "name") %>%
       select(name, ligand, nes)%>%
  pivot_wider(names_from = ligand, values_from = nes)


Reactome_sig_dm <- Reactome_sig %>%
  select(-name) %>%
  as.matrix()
rownames(Reactome_sig_dm) <- Reactome_sig$name

#any of the significantly enriched module 6+16 pathways include proteases and then which of these proteases are actually in 6+16.
# Interleukin−4 and Interleukin−13 signaling R-HSA-6785807
# Transcriptional regulation of granulopoiesis R-HSA-9616222
# Pre−NOTCH Transcription and Translation
# DNA Damage/Telomere Stress Induced Senescence R-HSA-2559586
# Pre−NOTCH Expression and Processing R-HSA-1912422
# FOXO−mediated transcription R-HSA-9614085

```


```{r create_heatmaps, fig.width=5, fig.height=12}

hm_Reactome <- Heatmap(Reactome_dm,
                       name = "NES",
                       column_title = "Reactome GSEA in MDD RNAseq",
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 1),
                       column_names_gp = gpar(fontsize = 6),
                       use_raster = FALSE)
hm_Reactome

write_csv(as.data.frame(Reactome_dm) %>%
  mutate(gene = rownames(Reactome_dm)) %>%
  select(gene, everything()), "../tables/MDD_RNAseq_Reactome_GSEA.csv")

Reactome_lists<- Reactome_all %>%
  select(name, size, es, nes, nom_p_val, fdr_q_val, fwer_p_val, rank_at_max, ligand) %>%
  mutate(es = round(es, 3),
         nes = round(nes, 3),
         nom_p_val = round(nom_p_val, 3),
         fdr_q_val = round(fdr_q_val, 3),
         fwer_p_val = round(fwer_p_val,3)) %>%
  split(.$ligand) 

res <- write_xlsx(Reactome_lists,
                  path = "../tables/MDD_Reactome_GSEA.xlsx")

Reactome_dm_noPBS <- Reactome_dm[,!str_detect(colnames(Reactome_dm),"PBS")]
hm_Reactome_noPBS <- Heatmap(Reactome_dm_noPBS,
                       name = "NES",
                       column_title = "Reactome GSEA in MDD RNAseq",
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 1),
                       column_names_gp = gpar(fontsize = 6),
                       use_raster = FALSE)
hm_Reactome_noPBS

res <- pdf("../plots/MDD_GSEA_Reactome.pdf", width = 5, height = 15)
draw(hm_Reactome)
draw(hm_Reactome_noPBS)
res <- dev.off()

write_csv(as.data.frame(Reactome_dm_noPBS) %>%
  mutate(gene = rownames(Reactome_dm_noPBS)) %>%
  select(gene, everything()), "../tables/MDD_RNAseq_noPBS_Reactome_GSEA.csv")

```


```{r create_significant_only_heatmaps, fig.width=5, fig.height=12}

hm_Reactome_sig <- Heatmap(Reactome_sig_dm,
                       name = "NES",
                       column_title = paste("Reactome GSEA in MDD RNAseq\nq thresh: ",fdr_q_thresh),
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 3),
                       column_names_gp = gpar(fontsize = 6),
                       use_raster = FALSE)
hm_Reactome_sig

write_csv(as.data.frame(Reactome_sig_dm) %>%
  mutate(gene = rownames(Reactome_sig_dm)) %>%
  select(gene, everything()), "../tables/MDD_RNAseq_Reactome_sig_GSEA.csv")


Reactome_sig_dm_noPBS <- Reactome_sig_dm[,!str_detect(colnames(Reactome_sig_dm),"PBS")]
hm_Reactome_sig_noPBS <- Heatmap(Reactome_sig_dm_noPBS,
                       name = "NES",
                       column_title = paste("Reactome GSEA in MDD RNAseq\nq thresh: ",fdr_q_thresh),
                       column_title_gp = gpar(fontsize = 12),
                       #col = colorRamp2(c(-2, 0, 2), c("#2166AC", "white", "#B2182B")),
                       cluster_rows = TRUE,
                       cluster_row_slices = FALSE,
                       cluster_columns = FALSE,
                       row_title = " ",
                       show_row_names = TRUE,
                   show_column_names = TRUE,
                       row_names_gp = gpar(fontsize = 3),
                       column_names_gp = gpar(fontsize = 6),
                       use_raster = FALSE)
hm_Reactome_sig_noPBS

res <- pdf("../plots/MDD_GSEA_Reactome_sig.pdf", width = 5, height = 15)
draw(hm_Reactome_sig)
draw(hm_Reactome_sig_noPBS)
res <- dev.off()

write_csv(as.data.frame(Reactome_sig_dm_noPBS) %>%
  mutate(gene = rownames(Reactome_sig_dm_noPBS)) %>%
  select(gene, everything()), "../tables/MDD_RNAseq_noPBS_Reactome_sig_GSEA.csv")

```

