---
title: "MDD supplemental figure 2"
date: "`r Sys.Date()`"
output: pdf_document

---

```{r "setup", include=FALSE}
knitr::opts_chunk$set(fig.width=14, fig.height=6,
                      echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)

#Author: Mark Dane, copyright 2015-2019
library(tidyverse)

```

```{r}

#' Read an assay's csv or tsv data file 
load_data <- function(assay_name, level = 4){
  file_name <- dir(path = "../",pattern = paste0("MDD_", assay_name,"_","Level",level),recursive = TRUE, full.names = TRUE)
  if(!length(file_name) == 1) stop("There was not one ", assay_name, " data file found")
    
  if(str_detect(file_name, "csv")) {
    df <- read_csv(file_name)
  } else if (str_detect(file_name, "tsv")){
    df <- read_tsv(file_name)
  } else stop("The data file ",file_name, " must be a csv or tsv file type")
} #end of function

```

```{r globalVariables}
ligand_cols <- c("ctrl" = "#7A4A2A",
                 "PBS" = "#8dd3c7",
                  "HGF" = "#80b1d3",
                  "OSM" = "#fdb462",
                  "EGF" = "#fb8072",
                  "BMP2" = "#b3de69",
                  "IFNG" = "#bebada",
                  "TGFB" = "#ffd92f")

 ligand2_cols <- c("EGF" = "#9E79A3", "none" = "#BE7249")

```

```{r readDataMetadata, echo=FALSE}

l3_data <- load_data(assay_name = "IF", level = 3)

l3 <- read_csv("../Metadata/MDD_sample_annotations.csv") %>%
  select(specimenID, ligand, experimentalCondition, secondLigand) %>%
  right_join(l3_data, by=c("specimenID"))

```



```{r boxplots}

#Add T0 normalized well cell count
l3_T0 <- l3 %>%
  filter(experimentalTimePoint == 0) %>% 
  group_by(collection, replicate) %>%
  mutate(WellCellCountT0Median = median(WellCellCount)) %>%
  ungroup() %>%
  select(collection, replicate, WellCellCountT0Median) %>%
      distinct() %>%
  right_join(l3, by = c("collection", "replicate")) %>%
  mutate(WellCellCountT0Norm = WellCellCount/WellCellCountT0Median,
         Ligand = str_remove(specimenName, "_.*"),
         Ligand = factor(Ligand, levels = names(ligand_cols)),
         Ligand2 = secondLigand,
         )
```

```{r cellCountBoxplots}

df <- l3_T0 %>%
  mutate(experimentalCondition = factor(experimentalCondition, levels = paste(c("ctrl", "PBS",  "HGF",  "OSM", "EGF",  "BMP2", "IFNG", "TGFB"), rep(c(0,24,48), each = 8), sep = "_")),
         experimentalConditionLigand = str_remove(experimentalCondition,"_.*"))
  

p <- ggplot(df, aes(x=experimentalCondition, y=WellCellCountT0Norm, fill=Ligand))+
  geom_boxplot(position = position_dodge(width=0.9), lwd = 1.1, outlier.colour = NA)+
  scale_fill_manual(values = ligand_cols) +
  scale_x_discrete(labels = c("ctrl", "PBS",  "HGF",  "OSM", "EGF",  "BMP\n+EGF2", "IFNG\n+EGF", "TGFB\n+EGF", "PBS",  "HGF",  "OSM", "EGF",  "BMP2\n+EGF", "IFNG\n+EGF", "TGFB\n+EGF")) +
  coord_cartesian(y = c(0,9)) +
  scale_y_continuous(breaks = c(1,3,5,7,9)) +
  labs(x="",
       y="Well Cell Count",
       title = "     0                                    24                                                               48") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=rel(1.5)),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1, size=rel(1.5)),
        plot.title = element_text(size = rel(2)),legend.text=element_text(size = rel(1)),
        legend.title=element_text(size = rel(1)))
p <- p + geom_vline(xintercept = c(1.5, 8.5), linetype="dashed")
p <- p +  geom_point(aes(shape=collection), color = "black", size = 3, position=position_jitterdodge(dodge.width=0.9), alpha=.6)

p


```
