---
title: "Reactome analysis of the MDD combined dataset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, cache.lazy = FALSE, message=FALSE, warning = FALSE, fig.height=10, fig.width=12)

suppressMessages(library(tidyverse))
library(readxl)
library(httr)
library(jsonlite)


create_pdfs <- TRUE
write_csvs <- TRUE

#dotplot filter values 
fdr_thresh <- .1
p_value_thresh <- .05
min_gene_nbr <- 1
max_gene_nbr <- 500
gene_ratio_thresh <- .1
keep_gene_nbr <- 5
pathway_nbr <- 5

```

Read in the cluster data from the integrated analysis, filter to RNA features and write out the gene symbols.  

```{r enrichr_reactome_pathways, eval = FALSE}
# Read in module xlsx file
###scratch code
# mod3_genes <- read_excel(file_name, sheet = "module_3") %>%
#     filter(Type == "RNAseq") %>%
#     select(feature) 
# write_csv(mod3_genes, "module_3_genes.csv")
# not_found_3 <- read_csv("not_found.csv") %>%
#   janitor::clean_names()
# mod3_genes_found <- mod3_genes %>%
#   filter(!feature %in% not_found_3$not_found)
# write_csv(mod3_genes_found, "module_3_genes_found.csv")
# 
# mod4_genes <- read_excel(file_name, sheet = "module_4") %>%
#     filter(Type == "RNAseq") %>%
#     select(feature) 
# write_csv(mod4_genes, "module_4_genes.csv")
# not_found_4 <- read_csv("not_found_4.csv") %>%
#   janitor::clean_names()
# mod4_genes_found <- mod4_genes %>%
#   filter(!feature %in% not_found_4$not_found)
# write_csv(mod4_genes_found, "module_4_genes_found.csv")

#####
#Run enrichr to get pathway data
excel_sheet_to_pathways <- function(sheet, file_name){
  pathways_list <- read_excel(file_name, sheet = sheet) %>%
    filter(Type == "RNAseq") %>%
    pull(feature) %>%
    enrichr(databases = "Reactome_2016")
  pathways_df <- pathways_list[[1]] %>%
    mutate(module = str_remove(sheet, "module_"))
  return(pathways_df)
}

if(!file.exists("MDD_enrichr_pathways.rda")){
  file_name <- "MDD_int_rr_combined_tables.xlsx"
  pathways <- map(excel_sheets(file_name), excel_sheet_to_pathways, file_name = file_name)
  
  #combine the module pathways, create geneRatio proportins
  #format pathway identifier and name
  enriched_pathways_enrichr <- bind_rows(pathways) %>%
    mutate(number_entities_found = str_remove(Overlap, "/.*"),
           number_entities_found = as.integer(number_entities_found),
           number_entities_total = str_remove(Overlap, ".*/"),
           number_entities_total = as.integer(number_entities_total),
           geneRatio = number_entities_found/number_entities_total,
           pathway_identifier = str_extract(Term, "R-HSA.*"),
           pathway_name = str_remove_all(Term, " R-HSA.*| Homo sapiens"),
           module = str_remove(module, "module_"),
           module = fct_inseq(module))%>%
    rename(entities_p_value = Adjusted.P.value)
  
  save(enriched_pathways_enrichr, file = "MDD_enrichr_pathways.rda")
} else {
  load("MDD_enrichr_pathways.rda")
}

selected_pathways_enrichr <- enriched_pathways_enrichr %>%
  group_by(module) %>%
  slice_min(order_by = c(entities_p_value), n = keep_gene_nbr, with_ties = FALSE) %>%
  slice_max(geneRatio, n = keep_gene_nbr, with_ties = FALSE) %>%
  ungroup() %>%
  dplyr::select(pathway_identifier)

# get_module_entrezgene_ids <- function(clust_num, write_csvs = FALSE){
#   data_path <- paste0("Tables/Ligand_clusters/MDD_ligand_cluster_",clust_num,"_features12.csv")
#   if(!file.exists(data_path)) stop("cannot load ",data_path)
#   gene_symbols <- read_csv(data_path) %>%
#     filter(Type == "RNA") %>%
#     pull(symbol) %>%
#     unique()
#   if(write_csvs){
#   write.table(gene_symbols,row.names = FALSE,sep = ",",
#               col.names = FALSE,quote = FALSE,
#               paste0("Tables/Ligand_clusters/MDD_ligand_cluster_",clust_num,"_symbols.csv"))
#   }
#   gene_ids <-getBM(attributes = c("hgnc_symbol", "entrezgene_id"),
#                       filters = "hgnc_symbol",
#                       values = gene_symbols,
#                       mart = ensembl) %>%
#   drop_na() %>%
#   dplyr::select(entrezgene_id)
#   return(gene_ids$entrezgene_id)
# }
# 

```


```{r reactome_API_pathways}

 get_pathway_data <- function(genes) {
   browser()
   #submit file of gene names to Reactome
   res <- POST(url = "https://reactome.org/AnalysisService/identifiers/projection/?interactors=false&species=Homo%20sapiens&pageSize=200&page=1&sortBy=ENTITIES_FDR&order=ASC&resource=TOTAL&pValue=1&includeDisease=true",
               body = genes,
               accept_json(),
               content_type("text/plain"))
   
   if(!status_code(res) == 200) stop("received API code ", status_code(res))
   
   #get res token
   res_token <- fromJSON(rawToChar(res$content))$summary$token
   
     #Identify Reactome  not found genes
     found <- GET(paste0("https://reactome.org/AnalysisService/download/",res_token,"/entities/found/TOTAL/result.csv"),
                      accept("text/plain"))
     reactome_genes <- rawToChar(found$content) %>%
       str_split("\n") %>%
       unlist() %>%
       tibble() %>%
       janitor::clean_names() %>%
       slice(n =-1) %>%
       mutate(Submitted_identifier = str_remove(x, ",.*")) %>%
       pull(Submitted_identifier) %>%
       unique()
     #Check that some of the genes are in reactome
     if(!identical(reactome_genes, "")){
        #submit file of found genes to Reactome
   pathway_res <- POST(url = "https://reactome.org/AnalysisService/identifiers/projection/?interactors=false&species=Homo%20sapiens&pageSize=200&page=1&sortBy=ENTITIES_FDR&order=ASC&resource=TOTAL&pValue=1&includeDisease=true",
             body = reactome_genes,
           accept_json(),
               content_type("text/plain"))
   
   if(!status_code(pathway_res) == 200) stop("received API code ", status_code(pathway_res))
   
   pathways <- fromJSON(rawToChar(pathway_res$content))$pathways 
   
   pathway_data <- pathways %>%
     select(-entities, -reactions, -species) %>%
     bind_cols(pathways$entities) %>%
     select(-exp) %>%
     mutate(geneRatio = found/total)
     } else {
       pathway_data <- NULL
     }
  
   return(pathway_data)
 }
 
#make a list with a character vector of gene names from each module
 get_genes_from_excel <- function(sheet_name, file_name){
     genes <- read_excel(file_name, sheet = sheet_name) %>%
    filter(Type == "RNAseq") %>%
       mutate(module = sheet_name) %>%
       select(module, feature)
     if(nrow(genes) == 0) return(NULL)
     return(genes$feature)
 }
 
 #make a list with a character vector of gene names from each module
 get_genes_from_previous_excel <- function(sheet_name, file_name){
     genes <- read_excel(file_name, sheet = sheet_name) %>%
    filter(assay == "RNA") %>%
       mutate(module = sheet_name) %>%
       select(module, symbol)
     return(genes$symbol)
 }
 
 if(!file.exists("MDD_Reactome_pathways_combined.csv")){
   file_name <- "MDD_int_rr_combined_tables.xlsx"
   gene_list <- map(excel_sheets(file_name), get_genes_from_excel, file_name = file_name)
   names(gene_list) <- excel_sheets(file_name)
       gene_list <- compact(gene_list)
   pathways_combined <- map_dfr(gene_list, get_pathway_data, .id = "module") %>%
         mutate(module = fct_inorder(module,ordered = TRUE))
   write_csv(pathways_combined, "MDD_Reactome_pathways_combined.csv")
 } else {
   pathways_combined <- read_csv("MDD_Reactome_pathways_combined.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))

 }
 
 #manually combine some modules based on biological review
  if(!file.exists("MDD_Reactome_pathways_combined_manual.csv")){
    file_name <- "MDD_int_rr_combined_tables.xlsx"
    gene_list <- map(excel_sheets(file_name), get_genes_from_excel, file_name = file_name)
    names(gene_list) <- excel_sheets(file_name)
    gene_list[["module_3+4"]] <- c(gene_list[[3]], gene_list[[4]])
    gene_list[["module_8+17"]] <- c(gene_list[[8]], gene_list[[17]])
    gene_list[["module_10+15"]] <- c(gene_list[[10]], gene_list[[15]])
    gene_list[c("module_3", "module_4", "module_8", "module_17", "module_10", "module_15")] <- NULL
          gene_list <- compact(gene_list)
   pathways_combined_manual <- map_dfr(gene_list, get_pathway_data, .id = "module") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
   write_csv(pathways_combined_manual, "MDD_Reactome_pathways_combined_manual.csv")
 } else {
   pathways_combined_manual <- read_csv("MDD_Reactome_pathways_combined_manual.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
 }
 
 
 #create API-based dotplot for unique modules
  if(!file.exists("MDD_Reactome_pathways_unique.csv")){
    file_name <- "MDD_int_rr_unique_tables.xlsx"
    gene_list <- map(excel_sheets(file_name), get_genes_from_excel, file_name = file_name)
    names(gene_list) <- excel_sheets(file_name)
    gene_list <- compact(gene_list)
   pathways_unique <- map_dfr(gene_list, get_pathway_data, .id = "module")
   write_csv(pathways_unique, "MDD_Reactome_pathways_unique.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
 } else {
   pathways_unique <- read_csv("MDD_Reactome_pathways_unique.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
 }
 
 #create API-based pathways for shared modules
  if(!file.exists("MDD_Reactome_pathways_shared.csv")){
    file_name <- "MDD_int_rr_shared_tables.xlsx"
    gene_list <- map(excel_sheets(file_name), get_genes_from_excel, file_name = file_name)
    names(gene_list) <- excel_sheets(file_name)
       gene_list <- compact(gene_list)
   pathways_shared <- map_dfr(gene_list, get_pathway_data, .id = "module")
   write_csv(pathways_shared, "MDD_Reactome_pathways_shared.csv")
 } else {
   pathways_shared <- read_csv("MDD_Reactome_pathways_shared.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
 }
 
  #get API-based pathways for previous modules
  if(!file.exists("MDD_Reactome_pathways_previous.csv")){
    file_name <- "MDD_int_rr_previous_tables.xlsx"
    gene_list <- map(excel_sheets(file_name), get_genes_from_previous_excel, file_name = file_name)
    names(gene_list) <- excel_sheets(file_name)
       gene_list <- compact(gene_list)
   pathways_previous <- map_dfr(gene_list, get_pathway_data, .id = "module")
   write_csv(pathways_previous, "MDD_Reactome_pathways_previous.csv")
 } else {
   pathways_previous <- read_csv("MDD_Reactome_pathways_previous.csv") %>%
         mutate(module = fct_inorder(module, ordered = TRUE))
 }
 
 
 # 
 # get_pathways <- function(dataset_type){
 #   browser()
 #   if(!file.exists(paste0("MDD_Reactome_pathways_",dataset_type,".csv"))){
 #     file_name <- paste0("MDD_int_rr_",dataset_type,"_tables.xlsx")
 #     gene_list <- map(excel_sheets(file_name), get_genes_from_excel, file_name = file_name)
 #     names(gene_list) <- excel_sheets(file_name)
 #     pathways<- map_dfr(gene_list, get_pathway_data, .id = "module")
 #     write_csv(pathways, paste0("MDD_Reactome_pathways_",dataset_type,".csv"))
 #   } else {
 #     pathways <- read_csv(paste0("MDD_Reactome_pathways_",dataset_type,".csv"))
 #   }
 # }
 # 

#pathways_unique <- get_pathways(dataset_type = "unique")


```


```{r load_manual_website_pathways, eval = FALSE}
# #manually load each gene set into Reactome and save  results files
# 
# Read in results files 
enriched_pathways_filenames<- dir("../integrated_analysis/Data",pattern = "result[[:digit:]]{1,2}.csv", full.names = TRUE) %>%
  str_sort(numeric = TRUE)

enriched_pathways_web <- map(enriched_pathways_filenames, read_csv,
                         col_types = cols(
  `Pathway identifier` = col_character(),
  `Pathway name` = col_character(),
  `#Entities found` = col_double(),
  `#Entities total` = col_double(),
  `Entities ratio` = col_double(),
  `Entities pValue` = col_double(),
  `Entities FDR` = col_double(),
  `#Reactions found` = col_double(),
  `#Reactions total` = col_double(),
  `Reactions ratio` = col_double(),
  `Species identifier` = col_double(),
  `Species name` = col_character(),
  `Submitted entities found` = col_character(),
  `Mapped entities` = col_logical(),
  `Found reaction identifiers` = col_character()
)) %>%
  bind_rows(.id = "module") %>%
  janitor::clean_names() %>%
  mutate(module = fct_inseq(module),
         geneRatio = number_entities_found/number_entities_total)

res <- write_csv(enriched_pathways_web, "Reactome_web_enriched_pathways_combined.csv")


```

```{r null_pathways, eval = FALSE}

enriched_pathways_web_null <- dir("../integrated_analysis/Null_Data",pattern = "resultn[[:digit:]]{1,2}.csv", full.names = TRUE) %>%
  str_sort(numeric = TRUE)

enriched_pathways_null <- map(enriched_pathways_web_null, read_csv) %>%
  bind_rows(.id = "module") %>%
  janitor::clean_names() %>%
  mutate(module = factor(module,levels = 1:length(enriched_pathways_web_null)),
         geneRatio = number_entities_found/number_entities_total)

```

```{r create_dotplots}

make_dotplots <- function(df, fdr_thresh = .2, gene_ratio_thresh = 0.1, pathway_nbr = 5, pathway_method = NULL){
 #browser()
   selected_pathways <- df %>%
  group_by(module) %>%
  slice_min(order_by = c(entities_p_value), n = pathway_nbr) %>%
  slice_max(geneRatio, n = pathway_nbr) %>%
  ungroup() %>%
  dplyr::select(pathway_identifier) %>%
     distinct()

df_selected <- df %>%
  right_join(selected_pathways, by = "pathway_identifier") %>%
  filter(entities_fdr <= fdr_thresh,
         geneRatio > gene_ratio_thresh) %>%
  group_by(pathway_name) %>%
  mutate(mean_fdr = mean(entities_fdr)) %>%
  ungroup() %>%
  arrange(desc(module), mean_fdr) %>%
  mutate(pathway_name = fct_inorder(pathway_name))

p <- ggplot(df_selected, aes(x = module,
                    y = pathway_name,
                    colour = entities_fdr,
                    size = geneRatio)) +
  geom_point() +
  scale_x_discrete(drop = FALSE) +
  scale_color_gradient(low = "red",high = "blue") +
  scale_size(range = c(0,4))+
  theme_bw() +
  theme(axis.text.y = element_text(size = 6,
                                   color = "black"))
p

 pdf(paste0("MDD_reactome_dotplot",pathway_method,".pdf"),
     width = 8,
     useDingbats = FALSE)
  print(p)
  dev_off_res <- dev.off()
}

make_dotplots_API <- function(df, fdr_thresh = .2, gene_ratio_thresh = 0.1, pathway_nbr = 5, pathway_method = NULL){
  #browser()
  selected_pathways <- df %>%
    group_by(module) %>%
    filter(fdr <= fdr_thresh,
           geneRatio >= gene_ratio_thresh) %>%
    slice_min(order_by = c(fdr), n = pathway_nbr) %>%
    slice_max(geneRatio, n = pathway_nbr) %>%
    ungroup() %>%
    dplyr::select(name) %>%
    distinct()
  
  df_selected <- df %>%
    right_join(selected_pathways, by = "name") %>%
    filter(fdr <= fdr_thresh,
           geneRatio >= gene_ratio_thresh) %>%
    group_by(name) %>%
    mutate(mean_fdr = mean(fdr),
           module = str_remove(module, "module_")) %>%
    ungroup() %>%
    mutate(module = fct_inorder(module, ordered = TRUE)) %>%
    arrange(desc(module), mean_fdr) %>%
    mutate(name = fct_inorder(name, ordered = TRUE))
  
  p <- ggplot(df_selected, aes(x = module,
                               y = name,
                               colour = fdr,
                               size = geneRatio)) +
    geom_point() +
    #scale_x_discrete(drop = FALSE) +
    scale_color_gradient(low = "red",high = "blue") +
    scale_size(range = c(0,4))+
    theme_bw() +
    theme(axis.text.y = element_text(size = 6,
                                     color = "black"),
          axis.text.x = element_text(angle = 90))
  p
  
  pdf(paste0("MDD_reactome_dotplot",pathway_method,".pdf"),
      width = 8,
      useDingbats = FALSE)
  print(p)
  dev_off_res <- dev.off()
}


# res <- make_dotplots(enriched_pathways_enrichr, pathway_method = "_enrichR")

# res <- make_dotplots(enriched_pathways_web, pathway_method = "_web")


res <- make_dotplots_API(pathways_combined, pathway_method = "_combined_API",fdr_thresh = 0.05, gene_ratio_thresh = 0.1)

res <- make_dotplots_API(pathways_combined_manual, pathway_method = "_combined_manual_API",fdr_thresh = 0.05, gene_ratio_thresh = 0.1)

res <- make_dotplots_API(pathways_unique, pathway_method = "_unique_API",fdr_thresh = 0.05, gene_ratio_thresh = 0.1)

  res <- make_dotplots_API(pathways_shared, pathway_method = "_shared_API",fdr_thresh = 0.05, gene_ratio_thresh = 0.1)

  res <- make_dotplots_API(pathways_previous, pathway_method = "_previous_API",fdr_thresh = 0.2, gene_ratio_thresh = 0.1)
  ##previous dataset analysis
#   
# path <- "../integrated_analysis/Data/MDD_ligand_module_features.xlsx"
# integrated_data <- lapply(readxl::excel_sheets(path), readxl::read_xlsx, path = path ) %>%
#   bind_rows(.id = "module") %>%
#   mutate(module = readxl::excel_sheets(path)[as.integer(module)])
# 
# int_genes <- integrated_data %>%
#   filter(assay == "RNA",
#          time %in% c(24,48)) %>%
#   rename(Cluster = module) %>%
#   select(Cluster, symbol) %>%
#   #mutate(Cluster = str_replace(Cluster, "module_","int_")) %>%
#   distinct
###
#   #####NULL dataset analysis
#   
#   selected_pathways_null <- enriched_pathways_null %>%
#   group_by(module) %>%
#   slice_min(order_by = c(entities_p_value), n = keep_gene_nbr) %>%
#   slice_max(geneRatio, n = keep_gene_nbr) %>%
#   ungroup() %>%
#   dplyr::select(pathway_identifier)
# 
# df <- enriched_pathways_null %>%
#   right_join(selected_pathways_null) %>%
#   filter(entities_p_value <= p_value_thresh,
#          geneRatio > gene_ratio_thresh) %>%
#   group_by(pathway_name) %>%
#   mutate(mean_fdr = mean(entities_fdr),
#          mean_p_value = mean(entities_p_value)) %>%
#   ungroup() %>%
#   arrange(desc(module), mean_p_value) %>%
#   mutate(pathway_name = fct_inorder(pathway_name))
# 
# p <- ggplot(df, aes(x = module,
#                     y = pathway_name,
#                     colour = entities_p_value,
#                     size = geneRatio)) +
#   geom_point() +
#   scale_x_discrete(drop = FALSE) +
#   scale_color_gradient(low = "red",high = "blue") +
#   scale_size(range = c(0,4))+
#   labs(title = "Null dataset") +
#   theme_bw() +
#   theme(axis.text.y = element_text(size = 6,
#                                    color = "black"))
# p
# 
#  pdf(paste0("MDD_null_dataset_reactome_dotplot.pdf"),
#      width = 8,
#      useDingbats = FALSE)
#   print(p)
#   dev_off_res <- dev.off()

```

###

